services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    env_file:
      - ./api/.env
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD} # .env의 값 참조
      MYSQL_DATABASE: ${DATABASE_NAME}
      TZ: Asia/Seoul
    volumes:
      - $HOME/data/mariadb:/var/lib/mysql
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"
      interval: 10s
      timeout: 5s
      retries: 3
  streaming:
    image: ossrs/srs:5
    volumes:
      - ./streaming/containers/data/config/:/usr/local/srs/containers/data/config/
      - ./streaming/containers/conf/srs.release-mac.conf:/usr/local/srs/conf/docker.conf
      # - ./streaming/containers/conf/srs.release.conf:/usr/local/srs/conf/docker.conf
      - ./streaming/containers/objs/nginx:/usr/local/srs/containers/objs/nginx
    ports:
      - 1935:1935 # rtmp
      - 1985:1985 #
      - 8080:8080
      - 8000:8000/udp
      - 10080:10080/udp
    network_mode: host
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - $HOME/data/redis:/data
