services:
  # rtmp:
  #   build: ./rtmp/
  #   ports:
  #     - 1935:1935
  #     - 8080:8080
  #   volumes:
  #     - ./hls:/tmp/hls
  #     - ./rtmp:/etc/nginx
  streaming:
    image: ossrs/srs:5
    volumes:
      - ./streaming/containers/data/config/:/usr/local/srs/containers/data/config/
      - ./streaming/containers/conf/srs.release-mac.conf:/usr/local/srs/conf/docker.conf
      - ./streaming/containers/objs/nginx:/usr/local/srs/containers/objs/nginx
    ports:
      - 1935:1935 # rtmp
      - 1985:1985 #
      - 8080:8080
      - 8000:8000/udp
      - 10080:10080/udp
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "$HOME/data/redis:/data"
volumes:
  video_stream_data:
